### ISSUE TITLE
generalize to other textLineOrder

### ISSUE THREAD

**Issue by bertsky** [qurator-spk/ocrd_repair_inconsistencies#3]
Currently the repair does not apply when the region's `@textLineOrder` is something other than `top-to-bottom`. But the code could easily be generalized to all allowed values (while still assuming `top-to-bottom` when nothing is annotated).

Moreover, IMO `readingDirection` should not be checked at all on the region vs line level (only on the line vs word and word vs glyph levels).

**Comment by mikegerber** [comment]
PR #4 looked good and addressed the issues I saw (like inheriting properties from the upper segments and not introducing untested code branches by supporting different orders/directions.)

I was also thinking about the one time when I saw a `bottom-to-top` region: It was an error in the PAGE file. However, this processor does enough sanity checking and would only change such a region if a. the order of lines is bad and b. the region text is also erroneously consistent with the line order error. So this would not be a problem.

**Comment by bertsky** [comment]
> I was also thinking about the one time when I saw a `bottom-to-top` region: It was an error in the PAGE file. However, this processor does enough sanity checking and would only change such a region if a. the order of lines is bad and b. the region text is also erroneously consistent with the line order error. So this would not be a problem.

Yes. I cannot image how one could have an agreement between the order in the textLineOrder/readingDirection annotation and the actual coordinates while still being wrong. But then again, there could be strange cases of polygonal shapes where the centroid does not tell you all that much. And the creator of that very annotation could have made the same assumption/error. So if the user does know this is impossible or unlikely, we could need an opt-out parameter.

One could still:
- deactivate the `reverse` behaviour with an additional parameter, say `only-top-down-left-right`, or
- dictate the only plausible order with an additional parameter, say `only-if-textlineorder-was` / `only-if-readingdirection-was`, (and thus even require `reverse=True` when e.g. `only-if-textlineorder-was='bottom-to-top'`).
